# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

import "lanes/BuildFastfile"
import "lanes/WorkflowFastfile"

platform :ios do
  before_all do
    ENV["XCODEPROJ"] = "FastlaneSample.xcodeproj"
    ENV["GIT_REPO"] = "matsuda/FastlaneSample"
  end
end
